[package]
name = "autd3-link-soem"
description = "autd3 link using SOEM"
readme = "README.md"
keywords = ["autd"]
version = "33.0.0"
authors = ["shun suzuki <suzuki@hapis.k.u-tokyo.ac.jp>"]
license = "MIT"
edition = "2024"
repository = "https://github.com/shinolab/autd3-link-soem"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[features]
default = ["local"]
blocking = ["remote", "tokio"]
local = ["ta", "cc", "glob", "anyhow", "time", "thiserror", "windows", "thread-priority", "spin_sleep", "getset", "autd3-core/utils"]
remote = ["autd3-protobuf", "tonic", "async"]
all = ["local", "remote"]
serde = ["dep:serde"]
async = ["autd3-core/async"]
async-trait = ["autd3-core/async-trait", "autd3-protobuf/async-trait"]

[dependencies]
autd3-core = { version = "33.0.0", default-features = false, features = ["link"] }
autd3-protobuf = { version = "33.0.0", optional = true }
crossbeam-channel = { version = "0.5.15", default-features = false, features = ["std"] }
derive_more = { version = "2.0.1", default-features = false }
getset = { version = "0.1.5", default-features = false, optional = true }
serde = { version = "1.0.219", optional = true, default-features = false }
spin_sleep = { version = "1.3.1", optional = true, default-features = false }
ta = { version = "0.5.0", optional = true, default-features = false }
thiserror = { version = "2.0.12", optional = true, default-features = false }
thread-priority = { version = "2.0.0", optional = true, default-features = false }
time = { version = "0.3.41", optional = true, default-features = false }
tokio = { version = "1.45.1", optional = true, default-features = false, features = ["rt-multi-thread"] }
tonic = { version = "0.13.1", optional = true, default-features = false }
tracing = { version = "0.1.41", default-features = false }
zerocopy = { version = "0.8.25", default-features = false }

[build-dependencies]
anyhow = { version = "1.0.98", optional = true, default-features = false }
cc = { version = "1.2.24", optional = true, default-features = false }
glob = { version = "0.3.2", optional = true, default-features = false }

[dev-dependencies]
anyhow = { version = "1.0.98", default-features = false }
autd3 = { version = "33.0.0", features = ["async"] }
tokio = { version = "1.45.1", default-features = false, features = ["rt-multi-thread"] }
tracing-subscriber = { version = "0.3.19", features = ["fmt"], default-features = false }

[target.'cfg(windows)'.dependencies]
windows = { version = "0.61.1", optional = true, default-features = false }

[[example]]
name = "soem"
path = "examples/soem.rs"
required-features = ["local"]

[[example]]
name = "remote_soem"
path = "examples/remote_soem.rs"
required-features = ["remote"]
