[package]
name = "autd3-link-soem"
description = "autd3 link using SOEM"
readme = "README.md"
keywords = ["autd"]
version = "29.0.0-rc.7"
authors = ["shun suzuki <suzuki@hapis.k.u-tokyo.ac.jp>"]
license = "MIT"
edition = "2021"
repository = "https://github.com/shinolab/autd3-link-soem"

[build-dependencies]
cc = { version = "1.0.73", features = ["parallel"], optional = true }
glob = { version = "0.3.0", optional = true }
anyhow = { version = "1.0.79", optional = true }

[dependencies]
serde = { version = "1.0.188", features = ["derive"], optional = true }
autd3-driver = { version = "29.0.0-rc.7" }
autd3-protobuf = { version = "29.0.0-rc.7", optional = true }
thiserror = { version = "2.0.0", optional = true }
time = { version = "0.3.23", features = ["std"], optional = true }
tonic = { version = "0.12.1", optional = true }
tokio = { version = "1.35.1", features = ["time"] }
async-channel = { version = "2.3.1", optional = true }
thread-priority = { version = "1.1.0", optional = true }
derive_more = { version = "1.0.0" }
tracing = { version = "0.1.40" }
ta = { version = "0.5.0", optional = true }
spin_sleep = { version = "1.2.1", optional = true }
zerocopy = { version = "0.8.7" }

[target.'cfg(windows)'.dependencies]
windows = { version = "0.58.0", features = ["Win32_Media_Multimedia", "Win32_System_Threading", "Win32_Foundation"], optional = true }

[target.'cfg(not(windows))'.dependencies]
libc = { version = "0.2.144", optional = true }

[features]
local = ["ta", "cc", "glob", "anyhow", "async-channel", "time", "thiserror", "windows", "libc", "thread-priority", "spin_sleep"]
remote = ["autd3-protobuf", "tonic"]
default = ["local"]
all = ["local", "remote"]
serde = ["dep:serde"]
async-trait = ["autd3-driver/async-trait", "autd3-protobuf/async-trait"]

[dev-dependencies]
anyhow = "1.0.79"
autd3 = { version = "29.0.0-rc.7" }
tokio = { version = "1.35.1", features = ["rt-multi-thread", "macros"] }
tracing-subscriber = "0.3.18"
